Array

In [1]:
import numpy as np
l = []
for i in range(1,3):
    a = int(input('Enter '))
    l.append(a)
b = np.array(l)
print(b)
print(b.ndim)


ValueError: invalid literal for int() with base 10: ''

In [6]:
ar2 = np.array([[1,2,3], [1,2,3]])
print(ar2)
print(ar2.ndim)

[[1 2 3]
 [1 2 3]]
2


In [7]:
ar3 = np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]
3


# Create 10 dimension array

In [9]:
arr = np.array([1,2,3], ndmin =10)
print(arr)
print(arr.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
10
