# Iteration

In [1]:
import numpy as np
a = np.array([5,4,7,6,3,2,9])
print(a)
for i in a:
    print(i)

[5 4 7 6 3 2 9]
5
4
7
6
3
2
9


In [3]:
a = np.array([[1,2,3,4],[5,7,6,3]])
print(a)
print()
for i  in a:
    print(i)
    
for i in a:
    for b in i:
        print(b)

[[1 2 3 4]
 [5 7 6 3]]

[1 2 3 4]
[5 7 6 3]
1
2
3
4
5
7
6
3


In [4]:
var = np.array([[[1,2,3,6,9,8],[5,6,1,7,9,3],[6,3,1,7,8,9]]])
for i in var:
    for j in i:
        for k in j:
            print(k)

1
2
3
6
9
8
5
6
1
7
9
3
6
3
1
7
8
9


In [6]:
var = np.array([[[1,2,3,6,9,8],[5,6,1,7,9,3],[6,3,1,7,8,9]]])
print(var)
print()
for i in np.nditer(var, flags=['buffered'], op_dtypes=['S']):
    print(i)

[[[1 2 3 6 9 8]
  [5 6 1 7 9 3]
  [6 3 1 7 8 9]]]

b'1'
b'2'
b'3'
b'6'
b'9'
b'8'
b'5'
b'6'
b'1'
b'7'
b'9'
b'3'
b'6'
b'3'
b'1'
b'7'
b'8'
b'9'


In [7]:
var = np.array([[[1,2,3,6,9,8],[5,6,1,7,9,3],[6,3,1,7,8,9]]])
print(var)
print()
for i,d in np.ndenumerate(var):
    print(i,d)

[[[1 2 3 6 9 8]
  [5 6 1 7 9 3]
  [6 3 1 7 8 9]]]

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 6
(0, 0, 4) 9
(0, 0, 5) 8
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 1
(0, 1, 3) 7
(0, 1, 4) 9
(0, 1, 5) 3
(0, 2, 0) 6
(0, 2, 1) 3
(0, 2, 2) 1
(0, 2, 3) 7
(0, 2, 4) 8
(0, 2, 5) 9
