# Join Array

In [2]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([8,6,3,2])
c = np.concatenate((a,b))
print(c)

[1 2 3 4 8 6 3 2]


In [5]:
a = np.array([[1,2],[2,6]])
b = np.array([[5,6],[8,9]])
c = np.concatenate((a,b), axis=1)
d = np.concatenate((a,b), axis=0)
print(c)
print()
print(d)

[[1 2 5 6]
 [2 6 8 9]]

[[1 2]
 [2 6]
 [5 6]
 [8 9]]


In [9]:
a = np.array([1,2,3,4])
b = np.array([8,6,3,2])
c = np.stack((a,b), axis = 1)
d = np.hstack((a,b)) #row
e = np.vstack((a,b)) #column
f = np.dstack((a,b)) # Height
print(c)
print()
print(d)
print()
print(e)
print()
print(f)

[[1 8]
 [2 6]
 [3 3]
 [4 2]]

[1 2 3 4 8 6 3 2]

[[1 2 3 4]
 [8 6 3 2]]

[[[1 8]
  [2 6]
  [3 3]
  [4 2]]]


# Split

In [10]:
a = np.array([5,2,3,9,7,4,5,6])
b = np.array_split(a, 3)
print(b)

[array([5, 2, 3]), array([9, 7, 4]), array([5, 6])]


In [12]:
a = np.array([[1,5,6,8],[8,3,6,7]])
b = np.array_split(a, 3)
c = np.array_split(a, 3, axis =1)
print(b)
print()
print(c)

[array([[1, 5, 6, 8]]), array([[8, 3, 6, 7]]), array([], shape=(0, 4), dtype=int32)]

[array([[1, 5],
       [8, 3]]), array([[6],
       [6]]), array([[8],
       [7]])]
