# Create Array with Functions

# Zeros

In [1]:
import numpy as np
arr_zero = np.zeros(2)
arr_zero1 = np.zeros((3,4))
print(arr_zero)
print()
print(arr_zero1)

[0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones

In [2]:
arr_ones = np.ones(1)
arr_ones_mult = np.ones((1,2))
print(arr_ones)
print(arr_ones_mult)

[1.]
[[1. 1.]]


# Empty

In [3]:
arr_empty = np.empty(6)
print(arr_empty)

[0. 0. 0. 0. 0. 0.]


# Range

In [4]:
arr_range = np.arange(1,5)
print(arr_range)

[1 2 3 4]


# Diagonal

In [5]:
arr_diag = np.eye(3)
print(arr_diag)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
arr_diag = np.eye(3,5)
print(arr_diag)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Linespace

In [7]:
arr_line = np.linspace(0,20, num=5)
print(arr_line)

[ 0.  5. 10. 15. 20.]
