# Random

# Rand()

In [2]:
import numpy as np
a = np.random.rand(4)
print(a)

[0.68528831 0.54929678 0.32901718 0.02981758]


In [3]:
# rand function is used to generate random numbers between 0 to 1

a = np.random.rand(3,3)
print(a)

[[0.0839817  0.13242909 0.28053135]
 [0.17638208 0.86506479 0.37868349]
 [0.43363434 0.49248327 0.19954741]]


# Randn

In [4]:
# randn is used to generate a random value close to zero. May Return positive or negative numbers.

a = np.random.randn(2)
print(a)

[ 1.27911743 -0.57616453]


In [5]:
a = np.random.randn(2,2)
print(a)

[[ 0.2291551   0.26053716]
 [ 0.15281392 -0.95335507]]


# Ranf

In [7]:
# randf returns an array of specified shape and fills it with random floats in interval [0.0, 1.0]

a = np.random.ranf(4)
print(a)

[0.47631922 0.77202415 0.98675384 0.29431276]


# Randint

In [9]:
# randint function is used to generate random number within a given range

a = np.random.randint(1,5,6)
print(a)

[1 2 1 2 3 1]
