# Data Type

In [2]:
import numpy as np
a = np.array([1,2,3,4])
print('Data Type ', a.dtype)

Data Type  int32


In [4]:
a = np.array([1.14, 2.15, 3.148,4])
print('Data Type ', a.dtype)

Data Type  float64


In [5]:
a = np.array(['a','b','c'])
print('Data Type ', a.dtype)

Data Type  <U1


In [8]:
a = np.array(['a','b','c','1'])
print('Data Type ', a.dtype)

Data Type  <U1


In [7]:
a = np.array(['a','b','c','1','2','2.5'])
print('Data Type ', a.dtype)

Data Type  <U3


In [9]:
a = np.array(['A','S','D','F',1,2,3])
print('Data Type ', a.dtype)

Data Type  <U11


# Change Datatype

In [11]:
a = np.array([1,2,3,4], dtype=np.int8)
print('Data Type ', a.dtype)

Data Type  int32


In [12]:
a = np.array([1,2,3,4], dtype='f')
print('Data Type ', a.dtype)
print(a)

Data Type  float32
[1. 2. 3. 4.]


In [13]:
a = np.array([1,2,3,4])

b = np.float32(a)

print('Data Type ', a.dtype)
print('Data Type ', b.dtype)

print(a)
print(b)

Data Type  int32
Data Type  float32
[1 2 3 4]
[1. 2. 3. 4.]


In [14]:
a = np.array([1,2,3,4])
b = np.float32(a)
c = np.int_(b)

print('Data Type ', a.dtype)
print('Data Type ', b.dtype)
print('Data Type ', c.dtype)

print(a)
print(b)
print(c)

Data Type  int32
Data Type  float32
Data Type  int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [15]:
a = np.array([1,2,3,4])
b = a.astype(float)

print(a)
print(b)
print('Data Type ', a.dtype)
print('Data Type ', b.dtype)

[1 2 3 4]
[1. 2. 3. 4.]
Data Type  int32
Data Type  float64
