# Arithmetic Operation

In [1]:
import numpy as np
a = np.array([1,2,3,4])
b = a + 4
print(b)

[5 6 7 8]


In [8]:
a = np.array([1,2,3,4])
b = np.reciprocal(a)
print(b)

[1 0 0 0]


In [2]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
c = a + b
print(c)

[2 4 6 8]


In [4]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
c = np.add(a,b)
print(c)

[2 4 6 8]


In [3]:
a = np.array([1,2,3,4])
b = a * 4
print(b)

[ 4  8 12 16]


# 2D Array

In [7]:
a = np.array([[1,2,3,4],[1,2,3,4]])
b = np.array([[1,2,3,4],[1,2,3,4]])
c = a + b
print(c)

[[2 4 6 8]
 [2 4 6 8]]


In [9]:
a = np.array([[1,2,3,4],[1,2,3,4]])
b = np.array([[1,2,3,4],[1,2,3,4]])
c = np.add(a, b)
print(c)

[[2 4 6 8]
 [2 4 6 8]]
