# Algebric Opeartions

In [5]:
import numpy as np
var = np.array([1,2,3,4,5,6,7])
print('Min: ',np.min(var), np.argmin(var))  # argmin means position of min value
print('Max: ',np.max(var), np.argmax(var)) # argmax means position of max value
print('Sqrt: ', np.sqrt(var))

Min:  1 0
Max:  7 6
Sqrt:  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131]


In [4]:
a = np.array([[1,8,3,4], [6,3,5,8]])
b = np.max(a, axis=1)
c = np.max(a, axis=0)
print(b)
print()
print(c)

[8 8]

[6 8 5 8]


In [9]:
a = np.array([0,1,2,3,4,90])
b = np.sin(a)
c = np.cos(a)
d = np.cumsum(a)
print(b)
print()
print(c)
print()
print(d)

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025   0.89399666]

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362 -0.44807362]

[  0   1   3   6  10 100]
