# Shape

In [3]:
import numpy as np
a = np.array([[1,2,3,4],[1,2,3,4]])
print(a)
print()
print(a.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [4]:
a = np.array([1,2,3,4], ndmin=4)
print(a)
print(a.ndim)
print(a.shape)

[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)


# Reshape

In [10]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)
print(a.ndim)

b = a.reshape(2,3,2)
print(b)
print(b.ndim)

c = b.reshape(-1)
print(c)
print(c.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
