# Broadcasting

In [3]:
import numpy as np

a = np.array([1,2,3,4])

print(a.shape)
print()
print(a)

b = np.array([[1],[2],[3]])
print(b.shape)
print()
print(b)
c = np.add(a, b)
print(c)

(4,)

[1 2 3 4]
(3, 1)

[[1]
 [2]
 [3]]
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [4]:
a = np.array([[1],[2]])
print(a.shape)
b = np.array([[1,2,3],[1,2,3]])
print(b.shape)
c = np.add(a,b)
print(c)

(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]
