# Indexing

In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a[1])

2


In [2]:
a = np.array([
            [1,2,3,4],
              [5,7,8,9]
])

print(a)
print()
print(a.ndim)
print()
print(a[1,3])

[[1 2 3 4]
 [5 7 8 9]]

2

9


In [3]:
a = np.array([[[1,2],[5,6]]])
print(a)
print()
print(a.ndim)
print()
print(a[0,1,1])

[[[1 2]
  [5 6]]]

3

6


In [6]:
a = np.array([[
    [1,2,3],
    [4,5,6],
    [7,8,9]]]
)
print(a)
print(a.ndim)
print()
print(a[0,2,2])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3

9


# Slicing

In [4]:
a = np.array([5,7,3,2,1,5,9,8,7,5,6,])
print(a[1:5])
print(a[1:])
print(a[:5])
print(a[::2])
print(a[1:8:2])

[7 3 2 1]
[7 3 2 1 5 9 8 7 5 6]
[5 7 3 2 1]
[5 3 1 9 7 6]
[7 2 5 8]


In [5]:
a = np.array([[1,2,3,4,5,6],[5,4,7,3,6,9],[5,1,7,3,6,8]])
print(a)
print()
print(a[1,1:])

[[1 2 3 4 5 6]
 [5 4 7 3 6 9]
 [5 1 7 3 6 8]]

[4 7 3 6 9]
