# Insert

In [10]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
b = np.insert(a, 4, 10) # 4 indicates the position
c = np.append(b, 25)
print(b)
print()
print(c)

[1 2 3 4]
[ 1  2  3  4 10]

[ 1  2  3  4 10 25]


In [7]:
a = np.array([[1,2,3],[4,5,6]])
b = np.insert(a, 2,6, axis=0)
c = np.insert(a, 1,6, axis=1)
print(b)
print()
print(c)

[[1 2 3]
 [4 5 6]
 [6 6 6]]

[[1 6 2 3]
 [4 6 5 6]]


# Delete

In [9]:
a = np.array([1,2,3,4])
b = np.delete(a, 2)
print(b)

[1 2 4]
