# Matrix

In [6]:
import numpy as np
a = np.matrix([[1,2,3,],[1,2,3]])
b = np.matrix([[1,2,3],[1,2,3]])
print(a)
print(type(a))
print()
print(a + b)
print()
# print(a * b)

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>

[[2 4 6]
 [2 4 6]]



In [9]:
b = np.array([[1,2,3],[1,2,3]])
c = np.array([[1,2,3],[1,2,3]])
print(b)
print(type(b))
print()
print(b * c)

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>

[[1 4 9]
 [1 4 9]]


In [8]:
var = np.matrix([[1,2],[1,2]])
var1 = np.matrix([[1,2],[1,2]])
print(var * var1)
print()
print(var.dot(var1))

[[3 6]
 [3 6]]

[[3 6]
 [3 6]]
