# Matrix Function

# Transpose

In [2]:
import numpy as np
var = np.matrix([[1,2,3],[7,8,9]])
print(var)
print()
print(np.transpose(var))
print()
print(var.T)

[[1 2 3]
 [7 8 9]]

[[1 7]
 [2 8]
 [3 9]]

[[1 7]
 [2 8]
 [3 9]]


# Swapaxes

In [3]:
var = np.matrix([[1,2,3],[7,8,9]])
print(np.swapaxes(var, 0,1))

[[1 7]
 [2 8]
 [3 9]]


In [5]:

print(var)
print()
print(np.swapaxes(var, 0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


# Inverse

In [6]:
var = np.matrix([[1,2],[3,4]])
print(var)
print()
print(np.linalg.inv(var))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


# Power

In [8]:
var = np.matrix([[1,2],[3,4]])
print(var)
print()
print(np.linalg.matrix_power(var,2))
print()
print(np.linalg.matrix_power(var,0))

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]


# Determinate

In [12]:
var = np.matrix([[1,2,9],[3,4,7],[4,7,6]])
print(var)
print()
print(np.linalg.det(var))

[[1 2 9]
 [3 4 7]
 [4 7 6]]

39.99999999999998
