# Search

In [2]:
import numpy as np
a = np.array([5,6,9,8,7,2,3,5,4,1,6,1,7,5,3,1,4,8,9,])
b = np.where(a == 1)
c = np.where((a%2) == 0)
print(b)
print()
print(c)

(array([ 9, 11, 15], dtype=int64),)

(array([ 1,  3,  5,  8, 10, 16, 17], dtype=int64),)


In [5]:
a = np.array([1,2,3,4,5,6,7,9])
b = np.searchsorted(a,8)
c = np.searchsorted(a, [8,9,10])
print(b)
print()
print(c)

7

[7 7 8]


# Sort

In [6]:
a = np.array([8,6,3,2,4,7,3,6,9,7,1,5,8,3,7])
b = np.sort(a)
print(b)

[1 2 3 3 3 4 5 6 6 7 7 7 8 8 9]


In [7]:
a = np.array(['a','s','d','f','r'])
b = np.sort(a)
print(b)

['a' 'd' 'f' 'r' 's']


In [8]:
a = np.array([[5,6,7],[9,2,7],[8,7,6]])
b = np.sort(a)
print(b)

[[5 6 7]
 [2 7 9]
 [6 7 8]]


# Filter Array

In [10]:
a = np.array([1,2,3,4])
b = [True, False, False, True]
c = a[b]
print(c)

[1 4]
