# Shuffle


In [3]:
import numpy as np
a = np.array([9,6,4,7,5,3,2,1])
np.random.shuffle(a)
print(a)

[6 4 7 2 9 3 1 5]


# Unique

In [6]:
a = np.array([5,6,2,4,5,6,2,1,4,5])
b = np.unique(a, return_index=True, return_counts=True)
print(b)

(array([1, 2, 4, 5, 6]), array([7, 2, 3, 0, 1], dtype=int64), array([1, 2, 2, 3, 2], dtype=int64))


# Resize

In [7]:
a = np.array([1,2,3,4,5,6])
b = np.resize(a, (2,3)) # Rows Columns
print(b)

[[1 2 3]
 [4 5 6]]


# Flatten

In [10]:
a = np.array([1,2,3,4,5,6])
b = np.resize(a, (2,3))
print(b)
print()
print('Flatten :',b.flatten(order='F'))
print('Ravel :', np.ravel(b))

[[1 2 3]
 [4 5 6]]

Flatten : [1 4 2 5 3 6]
Ravel : [1 2 3 4 5 6]
